### ISSUE TITLE
How to delete bookmarks ?

### ISSUE THREAD

**Issue by minzanupam** [artempyanykh/shellmark#1]
Well the problem is an simple as it sounds. 
I couldn't figure out how to delete a bookmark.

**Comment by minzanupam** [comment]
It was ctrl+k in browse mode

**Comment by shirts** [comment]
This should definitely be documented

**Comment by artempyanykh** [comment]
@shirts @Anupam-Ashish-Minz were you using the latest version? I think it should have F1 Help indicator in browse mode and a command in --help too.

**Comment by shirts** [comment]
@artempyanykh Yeah latest version. F1 works but there's no documentation about it that I can find. It was only obvious how to add something without having to look through source. 

Great tool. Thanks!

<img width="1059" alt="Screenshot 2024-06-28 at 10 52 50 AM" src="https://github.com/artempyanykh/shellmark/assets/4952151/a75957e0-e56b-4007-bd30-8f6caf3019a5">

**Comment by artempyanykh** [comment]
Do you have these in the browse mode's TUI @shirts ?
<img width="1279" alt="Screenshot 2024-07-06 at 13 28 20" src="https://github.com/artempyanykh/shellmark/assets/2338443/d7755abd-a3a6-472b-8332-903c0dcc30bd">
