### ISSUE TITLE
Installation in `zsh` fails

### ISSUE THREAD

**Issue by hemeroc** [artempyanykh/shellmark#3]
**Expected Behaviour:**
- Adding the lines from the `README.md` under https://github.com/artempyanykh/shellmark#integration-with-shell to `~/.zshrc` works

**Observed behaviour:**
- For simplicity I ran the command in zsh:
```shell
if type shellmark &>/dev/null; then
    eval "$(shellmark --out posix plug)"
fi

zsh: parse error near `}'
```
This happens reproduceable also when the command is copied into `~/.zshrc` and is then loaded via `source ~/.zshrc`.

**System Information:**
```shell
shellmark --version
shellmark 0.1.1
zsh --version
zsh 5.8.1 (x86_64-apple-darwin21.0)
```

**Comment by artempyanykh** [comment]
Hi @hemeroc ! Thanks for giving shellmark a go. I tried to repro (both on Mac and Linux) but couldn't.

I'm curious, what's the output of the following commands?
* `shellmark --out posix plug` gives you; 
* `eval "$(shellmark --out posix plug)"`
* `source <(shellmark -o posix plug)`?
* `type s`

**Comment by artempyanykh** [comment]
Update: I could repro after I installed shellmark via `cargo install shellmark` rather than from source.

**Comment by artempyanykh** [comment]
Looks like the problem was in a stray crlf line ending that threw off the shell. The problem didn't manifest with source builds because of git's auto crlf.

Anyhow, try installing the latest version '0.1.2' and let me know if it works for you.

**Comment by hemeroc** [comment]
Hi @artempyanykh, thank you very much for the fast response.
Yes the new version fixed it! Thanks a lot ❤️ keep up the great work!
