### ISSUE TITLE
Doesn't change to target dir on MacOS

### ISSUE THREAD

**Issue by Amparose** [artempyanykh/shellmark#4]
I have added a couple of bookmarks but when trying to navigate to one via Shellmark, `C-j` and `Enter` exit and print the path to CLI with `%` at the end.

M1, MacOS Ventura 13.2.1
Shellmark 0.2.3
Zsh

**Comment by artempyanykh** [comment]
Hi @Amparose! Did you invoke shellmark directly? Did you follow "Integration with the shell" part of [the README](https://github.com/artempyanykh/shellmark)? Please try adding shell integration and then invoke shellmark with `s` alias.

(I think I need improve README instruction a bit!)

**Comment by Amparose** [comment]
Well no... if I had done that it would have worked! Haha! Sorry for the trouble.

> (I think I need improve README instruction a bit!)

I think at very least add a step 4 to [Pre-built binary](https://github.com/artempyanykh/shellmark#pre-built-binary): "Integrate with shell".

I probably would not have missed it then.

**EDIT:** Now that I got it working, this is awesome! Thanks for a much-need CLI tool to get around.

**Comment by artempyanykh** [comment]
Happy to hear that it works now @Amparose!
