### ISSUE TITLE
Data storage location

### ISSUE THREAD

**Issue by Amparose** [artempyanykh/shellmark#5]
I haven't been successful in working out where Shellmark stores its data (on MacOS). Now I'd like to set up a new computer and migrate my shellmarks. Where are they stored?

**Comment by shirts** [comment]
@Amparose Looks like it's in the config directory. On MacOS you'll find it under:

`/Users/$USER/Library/Application\ Support/one.arr.shellmark`

**Comment by artempyanykh** [comment]
Good call! #6 adds a `diag` command that prints data location, count of bookmarks, and maybe more stuff in the future.
